language: cpp
services:
- xvfb
git:
  depth: false
install:
  - echo "clone lib2geom"
  - git clone https://gitlab.com/inkscape/lib2geom.git
  - pushd lib2geom
  - git checkout 37876ed4
  - popd
  - echo "configure lib2geom:"
  - cmake --version
  - cmake -GNinja
          -D2GEOM_TESTING=OFF
          -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
          -DCMAKE_C_COMPILER=${C_COMPILER}
          -B build-lib2geom
          -S lib2geom
  - sudo cmake --build build-lib2geom --target install
jobs:
  include:
  - os: linux
    dist: focal
    name: Build on Ubuntu Focal with GCC
    before_install:
    - build-scripts/install_build_deps_focal.sh
    - sudo apt install gdb
    script:
    - echo "using cmake-exe= ${cmake:-cmake}"
    - cmake -GNinja
            -DCMAKE_BUILD_TYPE=Debug
            -DQT_QM_PATH=/usr/share/qt5/translations/
            -DCMAKE_CXX_COMPILER=g++
            -DCMAKE_C_COMPILER=gcc
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -S .
            -B build
    - cmake --build build --target ommpfritt-cli
    - echo "  GDB start   GDB strat      GDB start"
    - gdb -batch -ex run -ex bt --args build/ommpfritt-cli status -c 'object name not found'
    - echo "  GDB end    GDB end   GDB end"
    - build/ommpfritt-cli status -c 'object name not found'
